apiVersion: apps/v1
kind: StatefulSet
metadata:
# User is required for Rancher to create the services automatically
  annotations:
    field.cattle.io/creatorId: user-qkgd2
  name: sql-data-generatordb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-architectonic-sql-data-generatordb
  serviceName: sql-data-generatordb
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.statefulset-architectonic-sql-data-generatordb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: sql-data-generatordb-secret
            optional: false
        image: sameersbn/postgresql:10-2
        imagePullPolicy: Always
        name: sql-data-generatordb
        ports:
        - containerPort: 5432
          name: postgressport
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: generatordb-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: generatordb-volume
        persistentVolumeClaim:
          claimName: sql-data-generatordb-pvc
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates: []
