version: '3.4'

services:
  architect-messenger:
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user1
    ports:
      - "15672:15672"
    volumes:
      - '${APPDATA-}/docker-volumes/rabbitmq_data:/data'

  architect-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AppSettings__IdentityUrl=http://architect-gateway/identity
      - AppSettings__ServiceGatewayUrl=http://architect-gateway
      - EventBus__EventBusConnection=architect-messenger
      - EventBus__EventBusUserName=user
      - EventBus__EventBusPassword=user1
    ports:
      - "80"

  architect-supplier:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  architect-notification:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  architect-generator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySqlProvider=server=sql-data-generatordb;database=generatordb;userid=admin;password=admin
    ports:
      - "80"

  architect-compiler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  architect-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  # Databases
  sql-data-generatordb:
    environment:
      - DEBUG=false
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=GeneratorDb
    ports:
      - "15432:5432"
    volumes:
      - ${APPDATA-}/docker-volumes/sql-data-dataaccesslayer:/var/lib/postgresql/data
