version: '3.4'

services:
  architect-messenger:
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user1
    ports:
      - "15672:15672"
    volumes:
      - '${APPDATA-}/docker-volumes/rabbitmq_data:/data'

  architect-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://architect-gateway/identity
      - ServiceGatewayUrl=http://architect-gateway
      - EventBusSettings__EventBusConnection=architect-messenger
      - EventBusSettings__EventBusUserName=user
      - EventBusSettings__EventBusPassword=user1
      - EventBusSettings__SubscriptionClientName=Web
      - EventBusSettings__EventBusRetryCount=5
    ports:
      - "51841:80"

  architect-supplier:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9004:80"

  architect-notification:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9003:80"

  architect-generator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DataAccessPostgreProvider=Host=sql-data-generatordb;Port=5432;Username=admin;Password=admin;Database=GeneratorDb;
      - EventBusSettings__EventBusConnection=architect-messenger
      - EventBusSettings__EventBusUserName=user
      - EventBusSettings__EventBusPassword=user1
      - EventBusSettings__SubscriptionClientName=Web
      - EventBusSettings__EventBusRetryCount=5
    ports:
      - "9002:80"

  architect-compiler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - EventBusSettings__EventBusConnection=architect-messenger
      - EventBusSettings__EventBusUserName=user
      - EventBusSettings__EventBusPassword=user1
      - EventBusSettings__SubscriptionClientName=Web
      - EventBusSettings__EventBusRetryCount=5
    ports:
      - "9001:80"

  architect-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  # Databases
  sql-data-generatordb:
    environment:
      - DEBUG=false
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=GeneratorDb
    ports:
      - "15432:5432"
    volumes:
      - ${APPDATA-}/docker-volumes/sql-data-dataaccesslayer:/var/lib/postgresql/data
