version: '3.4'

services:

  architect-messenger:
    image: rabbitmq:3-management-alpine

  architect-web:
    image: ${DOCKER_REGISTRY-}arweb
    build:
      context: .
      dockerfile: src/Ar.WebApp/Ar.Web/Dockerfile
    depends_on:
      - architect-messenger
      - architect-gateway

  architect-supplier:
    image: ${DOCKER_REGISTRY-}arsupplierapi
    build:
      context: .
      dockerfile: src/Ar.Services/Supplier.Service/Ar.Supplier.Api/Dockerfile


  architect-notification:
    image: ${DOCKER_REGISTRY-}arnotificationapi
    build:
      context: .
      dockerfile: src/Ar.Services/Notification.Service/Ar.Notification.Api/Dockerfile


  architect-generator:
    image: ${DOCKER_REGISTRY-}argeneratorapi
    build:
      context: .
      dockerfile: src/Ar.Services/Generator.Service/Ar.Generator.Api/Dockerfile
    depends_on:
      - sql-data-generatordb
    command: /bin/bash -c "until nc -z sql-data-generatordb 5432; do echo waiting for sql-data-generatordb; sleep 60; done;"


  architect-compiler:
    image: ${DOCKER_REGISTRY-}arcompilerapi
    build:
      context: .
      dockerfile: src/Ar.Services/Compiler.Service/Ar.Compiler.Api/Dockerfile


  architect-gateway:
    image: ${DOCKER_REGISTRY-}argateway
    build:
      context: .
      dockerfile: src/Ar.ApiGateways/Ar.Gateway/Dockerfile

  # Databases
  sql-data-generatordb:
    image: sameersbn/postgresql:10-2

