apiVersion: apps/v1
kind: Deployment
metadata:
# User is required for Rancher to create the services automatically
  annotations:
    field.cattle.io/creatorId: user-qkgd2
    field.cattle.io/publicEndpoints: '[{"port":443,"protocol":"HTTPS","serviceName":"architectonic:architect-web","ingressName":"architectonic:architect-web-ingress","hostname":"architectonic.localhost","path":"/","allNodes":false}]'
  name: architect-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-architectonic-architect-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-architectonic-architect-web
    spec:
      affinity: {}
      containers:
      - envFrom:
        - configMapRef:
            name: environment-configmap
            optional: false
        - configMapRef:
            name: architect-web-configmap
            optional: false
        - configMapRef:
            name: eventbus-settings-configmap
            optional: false
        - secretRef:
            name: eventbus-settings-secret
            optional: false
        image: evolynsky/architectonic:arweb
        imagePullPolicy: Always
        name: architect-web
        ports:
        - containerPort: 80
          name: ingressport
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command: ['sh', '-c', 'until nslookup architect-messenger; do echo waiting for architect-messenger; sleep 2; done;']
        image: busybox:latest
        imagePullPolicy: Always
        name: init-architect-messenger
      - command: ['sh', '-c', 'until nslookup architect-gateway; do echo waiting for architect-gateway; sleep 2; done;']
        image: busybox:latest
        imagePullPolicy: Always
        name: init-architect-gateway
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
