apiVersion: apps/v1
kind: Deployment
metadata:
# User is required for Rancher to create the services automatically
  annotations:
    field.cattle.io/creatorId: user-qkgd2
  name: architect-compiler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-architectonic-architect-compiler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-architectonic-architect-compiler
    spec:
      affinity: {}
      containers:
      - envFrom:
        - configMapRef:
            name: environment-configmap
            optional: false
        - configMapRef:
            name: eventbus-settings-configmap
            optional: false
        - configMapRef:
            name: architect-compiler-configmap
            optional: false
        - secretRef:
            name: eventbus-settings-secret
            optional: false
        image: evolynsky/architectonic:arcompilerapi
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30