apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/description: The resources included in the namespace build the
      Architectonic application
    field.cattle.io/projectId: local:p-kwsrc
  name: architectonic
