# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: architectonic

# Labels to add to all resources and selectors.
commonLabels:
  owner: Evgeny Volynsky 
  application: Architectonic
  stage: development
  version: ver-0.1
  
# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
#Secrets
- /secrets/digitalocean-secret.yaml
#ConfigMaps
#Pvc
#Stateful sets
#Deployments
 