apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data-generatordb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
